version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - dependencies

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - dependencies

  - package-ecosystem: "npm"
    directory: "/e2e"
    schedule:
      interval: "daily"
    labels:
      - dependencies
