name: 🚀 Feature Request
description: Suggest an idea for this project
title: "feat(_subject_): "
labels:
  - "enhancement"
assignees:
  - douglasduteil
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: A clear and concise description of the feature you are proposing.
    validations:
      required: true
