#

name: scalingo/buildpack

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          commit_message: ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: scalingo/buildpack
          publish_dir: ./.scalingo/buildpack
          # NOTE(douglasduteil): do not add .nojekyll file
          enable_jekyll: true
