#

name: scalingo/buildpack

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  push:
    name: Sync scalingo/buildpack branch with .scalingo/buildpack folder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        if: github.ref == 'refs/heads/master'
        with:
          commit_message: ${{ github.event.head_commit.message }}
          enable_jekyll: true # NOTE(douglasduteil): do not add .nojekyll file
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: scalingo/buildpack
          publish_dir: ./.scalingo/buildpack
          user_email: "github-actions[bot]@users.noreply.github.com"
          user_name: "github-actions[bot]"
