#

name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
      - name: Install bun
        uses: oven-sh/setup-bun@v1.2.1
      - run: bun install --frozen-lockfile
      - run: bun run build
      - run: bun run test
