#

name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Install bun
        uses: oven-sh/setup-bun@123c6c4e2fea3eb7bffaa91a85eb6b3d505bf7af # v2
      - run: bun install --frozen-lockfile
      - run: bun run build
      - run: bun run test:type-check
      - run: bun test
          --coverage
          --coverage-reporter=lcov
          --coverage-reporter=text
