#

name: 🚢 Release It !

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
      - run: bun x release-it
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
