#

name: Publish package to GitHub Packages
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "latest"
          registry-url: "https://npm.pkg.github.com"
          scope: "@betagouv"
      - run: npm publish --access=public --tag alpha
        working-directory: ./packages/trpc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
