#

name: 🕵️ Sentry

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  release:
    name: Sentry Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
        with:
          fetch-depth: 0
      - uses: getsentry/action-release@v1.7.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: sentry
          SENTRY_PROJECT: hyyypertool
          SENTRY_URL: https://errors.data.gouv.fr
        with:
          environment: production
